feat(docs): add initial structure
he4rt/react4noobs pull request #137
Opened 2023-10-18 02:21 UTC by gabrielduete

Closes: https://github.com/he4rt/react4noobs/issues/127

2023-10-20 11:27 UTC, Bluniz commented
Artigo está muito bom, é um tema bem importante por sinal. Uma sugestão é alterar o local onde ela está, pois error Boundary ta mais pra uma API do React do que uma Design Pattern. Faz sentido para ti?

2023-10-20 11:43 UTC, Bluniz commented
O artigo está muito bom, parabéns!

Alguns pontos Importantes: 

- A localização do artigo está meio incompatível com oque ele é, pois `ErrorBoundary` é basicamente uma aplicação do `componentDidCatch` e api do React, não uma design pattern ao meu ver. Faz sentido pra ti?

- Acredito que o foco do artigo ficou muito em explicar o que é, porém mostrou como fazer apenas no uso de uma lib. Seria bom ter um exemplo de como seria fazer normalmente, sem nenhuma biblioteca pois o foco é este, ensinar como fazer sem nada extra, mostrar as limitações e então dar uma possibilidade com uma biblioteca. (Temos sempre que se preocupar em não depender de bibliotecas).

- Senti falta da explicação que quando acontece um erro não tratado(crasha), o react desmonta toda a tela.

- Também acredito que é importante falar da possibilidade do uso para observabilidade, ou seja poder registrar onde e quando ocorreu um erro na aplicação. (Aqui apenas a nível informativo)

- Também, mostrar a possibilidade de da pessoa que for utilizar o errorBoundary poder pegar o StackTrace do erro e mostrar de uma forma mais bonita sem desmontar a tela.

Sobre exemplos de uso, tem um repo que talvez possa ajudar:
https://github.com/Bluniz/micro-front/blob/master/container/src/components/ErrorBoundary/index.jsx

2023-10-20 11:44 UTC, Bluniz requested changes
O artigo está muito bom, parabéns!

Alguns pontos Importantes:

A localização do artigo está meio incompatível com oque ele é, pois ErrorBoundary é basicamente uma aplicação do componentDidCatch e api do React, não uma design pattern ao meu ver. Faz sentido pra ti?

Acredito que o foco do artigo ficou muito em explicar o que é, porém mostrou como fazer apenas no uso de uma lib. Seria bom ter um exemplo de como seria fazer normalmente, sem nenhuma biblioteca pois o foco é este, ensinar como fazer sem nada extra, mostrar as limitações e então dar uma possibilidade com uma biblioteca. (Temos sempre que se preocupar em não depender de bibliotecas).

Senti falta da explicação que quando acontece um erro não tratado(crasha), o react desmonta toda a tela.

Também acredito que é importante falar da possibilidade do uso para observabilidade, ou seja poder registrar onde e quando ocorreu um erro na aplicação. (Aqui apenas a nível informativo)

Também, mostrar a possibilidade de da pessoa que for utilizar o errorBoundary poder pegar o StackTrace do erro e mostrar de uma forma mais bonita sem desmontar a tela.

Sobre exemplos de uso, tem um repo que talvez possa ajudar:
https://github.com/Bluniz/micro-front/blob/master/container/src/components/ErrorBoundary/index.jsx

2024-01-08 07:26 UTC, gabrielduete commented
Salve, @rosajsx! Vim aqui finalmente resolver essa PR ahuauh! 

Valeu demais, mano!! Excelentes pontos! ❤️ 

- Adicionei um exemplo de Error Boundaries com componentes de classe e realoquei para a seção de iniciando com React: 
	- https://github.com/he4rt/react4noobs/pull/137/commits/4240d1cfd2fe46427343e96327ccde0a5fabd20a
	- https://github.com/he4rt/react4noobs/pull/137/commits/ba336f566157162f30047a88832d175a7b1e35bb
- No exemplo do método `onError` deixei uma explicação extra sobre o crash onde o react desmonta a tela: 
	- https://github.com/he4rt/react4noobs/pull/137/commits/514199ff84bc8fb8123f561106bf7533b97692ef
- Adicionei exemplo sobre observabilidade do erro:
	- https://github.com/he4rt/react4noobs/pull/137/commits/2e854a33b99468e97dbdaa86a9cfb431ee7d1295
- Adicionei um exemplo utilizando o error boundaries para pegar o stack tracer:
	- https://github.com/he4rt/react4noobs/pull/137/commits/2dae98930373207e76ae175d3c3ae08fa7bc1176

2024-01-10 14:03 UTC, rosajsx commented
Fala mano @gabrielduete sempre bom ver teus PR`S, me animam a continuar o repo, hehe!

Mano, novamente muito parabéns! O conteúdo está muito bom, gostei muito da forma como tu foi levando o leitor a chegar a necessidade de usar o `ErrorBoundary` realmente muito bom. 

Fiz só um comentário ali de detalhe mesmo, coisa besta! Ajeitando isso a gente já sobe ele e vamo de dale em todo o resto!

Muito obrigado, hehe!

2024-06-18 21:38 UTC, gabrielduete commented
Salve, grande @rosajsx ! Tudo certo? (Quanto tempo eim, mano, slc! <3) 

E... novamente eu deixei cair a PR no esquecimento.. desculpa, mano!

> Fiz só um comentário ali de detalhe mesmo, coisa besta! Ajeitando isso a gente já sobe ele e vamo de dale em todo o resto!
Esses ajustes apliquei nesses commits aqui: https://github.com/he4rt/react4noobs/pull/137#issuecomment-1880495516

Acha que falta mais alguma coisa?

2024-07-04 10:13 UTC, rosajsx commented
Fala meu mano @gabrielduete, quanto tempo ein? Hihiihhi

Eai, vamos voltar a finalizar o repo? 
Achei perfeito todas as alterações, creio eu que não falta mais nada! Ta ótimo hihihii! Aprovado!

2024-07-04 10:13 UTC, rosajsx approved these changes

2024-07-04 10:13 UTC, merged

2024-07-04 21:10 UTC, gabrielduete commented on docs/Iniciando com React/9-React Error Boundaries.md
> +Antes do React 16 as aplicações costumavam crashar quando ocorria algum erro de javascript, como por exemplo erro de tipagem. Os componentes corrompiam o estado interno e retornavam erros imcompreens
Faz sentido demais, mano! Vou abrir uma PR pra subir essas correções

2024-07-04 21:10 UTC, gabrielduete commented
> Eai, vamos voltar a finalizar o repo?

Lets bora