Features/tests/midhatdrops
he4rt/react4noobs pull request #63
Opened 2021-04-07 19:25 UTC by midhatdrops

Add feature: Testes de integração

Update Features: Doc README e Colaborators.

2021-04-08 14:48 UTC, AnnaCampelo requested changes
Primeiramente obrigada pela sua contruibuição, já estava com saudades de ficar lendo PRs hahahaha

Deixei alguns comentários, nada muito grave, mas importante nos atentar. 🐶

2021-04-08 14:48 UTC, AnnaCampelo commented on docs/Testes/1-testes-unitarios.md
> +Testes unitários podem ser definidos como porções de códigos responsáveis por validar o comportamento de unidades funcionais de código, sendo unidades funcionais qualquer componente que através de su
```suggestion
Testes unitários podem ser definidos como porções de códigos responsáveis por validar o comportamento de unidades funcionais de código, sendo unidades funcionais de qualquer componente que através de sua invocação possa gerar o resultado esperado. Podemos, então, pensar inicialmente em testes unitários no contexto de funções puras, que por sua vez são funções as quais não alteram o estado da nossa aplicação, tal como uma função de soma de dois números. Segue um exemplo:
```

2021-04-08 14:48 UTC, AnnaCampelo commented on docs/Testes/1-testes-unitarios.md
> +Porém, podemos expandir o conceito de teste unitários para coisas mais complexas, como por exemplo, no contexto do React, a renderização de um componente e verificar se o mesmo é renderizado, se é re
```suggestion
Porém, podemos expandir o conceito de teste unitários para coisas mais complexas. 
Por exemplo, no contexto do React, a renderização de um componente é verificar se o mesmo é renderizado, se é renderizado com o comportamento esperado e até mesmo se está lidando com eventos do próprio componente tais como cliques da maneira correta.
```

2021-04-08 14:48 UTC, AnnaCampelo commented on docs/Testes/1-testes-unitarios.md
> +TDD, ou Test-Driven Development (Desenvolvimento Orientado a Testes) é uma técnica de desenvolvimento de software fundamental para a validação de uma aplicação, muito utilizada pelas empresas e cobra
Quando você menciona 

> Essa prática minimiza os erros da aplicação, garantindo que em ambiente de produção ela ocorra da forma esperada.

Não pareceu claro para mim, o que precisa acontecer em um ambiente de produção pra "ocorrer de forma esperada"?

2021-04-08 21:47 UTC, midhatdrops commented
Olá Anna. Primeiro, eu que agradeço pela revisão, as vezes mandamos PR's e o pessoal nem revisa a parte textual, graças às suas indicações pude ver que em algumas partes constavam erros de português e outras poderiam ser aprimoradas. Enfim, adotei suas sugestões e quanto a dúvida da linha 27, alterei o texto e espero que dessa vez  o texto esteja esclarecendo.

Sigo aberto também para mais sugestões ou melhorias, obrigado!

2021-04-09 14:28 UTC, AnnaCampelo approved these changes
Certinho, Bruno.

Ótimo conteúdo, parabéns 🎉🎉

2021-04-09 14:28 UTC, merged