Artigo Next.js
he4rt/react4noobs pull request #72
Opened 2021-06-26 20:25 UTC by joaobispo2077

Fala pessoal!

Demorei, mas finalmente finalizei o conteúdo. Esse PR é o artigo de [Next.js](https://github.com/he4rt/react4noobs/issues/50).

Cubro uma introdução de conceitos como os modelos de renderização e motivos/encorajamento de uso do Next.js, também demonstrei como seria a utilização prática desse framework na criação de um projeto simples.

Acabei me empolgando na hora de produzir e fiz tudo em um mono arquivo gigante que
acredito que precisa ser quebrado em arquivos menores.

Então, a minha proposta é que conforme eu vá quebrando em arquivos menores, facilite tanto
o consumo quanto a revisão que outro alguém possa fazer sobre o conteúdo.

2021-06-26 22:13 UTC, jos3s requested changes
Organização dos arquivos

2021-06-26 22:13 UTC, jos3s commented on docs/Frameworks/nextjs/1-Introducao.md
> +      </ol>
Você pode construir essa mesma tabela apenas usando Markdown poderia ser bem melhor do que usar elementos HTML nesse caso.

2021-06-26 22:13 UTC, jos3s commented on docs/Frameworks/nextjs/1-Introducao.md
> +      </ol>
Você poderia dividir em dois arquivos, um com os conceitos e um com a implementação em um projeto, facilitaria a hora da leitura.

2021-06-27 23:47 UTC, joaobispo2077 commented on docs/Frameworks/nextjs/1-Introducao.md
> +      </ol>
Fala José, sobre a conversão de HTML para Markdown, inicialmente, vejo como somente duas formas diferentes de se fazer uma mesma coisa, mas se o intuito da sua recomendação foi a facilidade de manutenção. Concordo que faz sentido mudar para markdown e acabo de fazer a alteração.

2021-06-27 23:49 UTC, joaobispo2077 commented on docs/Frameworks/nextjs/1-Introducao.md
> +      </ol>
Na divisão do mono arquivo em dois menores, você acha que faz sentido que eu quebre em diversos arquivos menores?  Dado que o desafio dos conceitos e do Projeto pode parecer muito maior do que realmente é estando em somente 2 arquivos grandes. Obrigado pelas recomendações @jos3s!

2021-06-27 23:53 UTC, jos3s commented on docs/Frameworks/nextjs/1-Introducao.md
> +      </ol>
Acredito que a divisão em duas partes já seria suficiente, o que aumenta o tamanho dos arquivos é os exemplos dos códigos.

2021-06-27 23:55 UTC, jos3s commented on docs/Frameworks/nextjs/1-Introducao.md
> +      </ol>
> Fala José, sobre a conversão de HTML para Markdown, inicialmente, vejo como somente duas formas diferentes de se fazer uma mesma coisa, mas se o intuito da sua recomendação foi a facilidade de manutenção. Concordo que faz sentido mudar para markdown e acabo de fazer a alteração.

Eu sempre tenho o pensamento de evitar usar HTML no Markdown, exceto em casos como centralizar texto ou adicionar outras coisas que o Markdown não suporta, é sempre bom usar o máximo do que é nativo pra linguagem

2021-06-28 13:14 UTC, joaobispo2077 commented on docs/Frameworks/nextjs/1-Introducao.md
> +      </ol>
> > Fala José, sobre a conversão de HTML para Markdown, inicialmente, vejo como somente duas formas diferentes de se fazer uma mesma coisa, mas se o intuito da sua recomendação foi a facilidade de manutenção. Concordo que faz sentido mudar para markdown e acabo de fazer a alteração.
> 
> Eu sempre tenho o pensamento de evitar usar HTML no Markdown, exceto em casos como centralizar texto ou adicionar outras coisas que o Markdown não suporta, é sempre bom usar o máximo do que é nativo pra linguagem

Entendi, muito obrigado pelo insight!

2021-06-28 13:26 UTC, joaobispo2077 commented on docs/Frameworks/nextjs/1-Introducao.md
> +      </ol>
> Acredito que a divisão em duas partes já seria suficiente, o que aumenta o tamanho dos arquivos é os exemplos dos códigos.

Realmente,  sendo exemplo de código ou explicação, continuam desafiadores. Subi uma alteração fazendo a separação em Introdução, Conceitos, Projeto e Extras. 

Nessa separação, a Introdução seria a referência de todo o artigo de Next.Js, a parte do Conceitos um local para sempre que alguém se interessar explicar um conceito do Next.js, o projeto com exemplo prático dos conceitos de modelo de renderização e a parte de Extras um local para dar suporte a práticas/recursos interessantes que não foram trabalhadas no projeto, como por exemplo o suporte ao Typescript ou futuramente alguém adicionar um trecho sobre Internacionalização.

Ainda pretendo revisar cada trecho antes de tirar essa PR de draft, obrigado pelos feedbacks velozes!

2021-06-28 16:22 UTC, jos3s commented on docs/Frameworks/nextjs/2-Conceitos.md
> +- *Setup zero config* -> Quando iniciamos um projeto React.JS ou um projeto front-end qualquer, nós precisamos configurar um esquema de roteamento para navegação entre páginas, normalmente no context
Falta o link com o arquivo do react-router-dom

2021-06-28 16:57 UTC, jos3s commented on docs/Frameworks/nextjs/1-Introducao.md
> +1. Conceitos
Como separou os arquivos agora os links não funcionam mais, não sei se é possível fazer um link no markdown para uma determinada posição de outro arquivo. Se não for possível apenas deixe um sumário com o link para o arquivo e em cada arquivo você replica a tabela de conteúdo do arquivo

2021-07-05 00:58 UTC, jos3s commented on docs/Frameworks/nextjs/1-Introducao.md
> +1. [Conceitos](https://github.com/he4rt/react4noobs/blob/master/docs/Frameworks/nextjs/2-Conceitos.md)
Você não precisa fornecer um link para o arquivo no github pode fazer o link com os caminhos relativos localmente, que vai funcionar na web

2021-07-05 00:58 UTC, jos3s commented on docs/Frameworks/nextjs/1-Introducao.md
> +2. [Projeto](https://github.com/he4rt/react4noobs/blob/master/docs/Frameworks/nextjs/3-Projeto.md)
Você não precisa fornecer um link para o arquivo no github pode fazer o link com os caminhos relativos localmente, que vai funcionar na web

2021-07-12 00:15 UTC, joaobispo2077 commented on docs/Frameworks/nextjs/1-Introducao.md
> +2. [Projeto](https://github.com/he4rt/react4noobs/blob/master/docs/Frameworks/nextjs/3-Projeto.md)
Valeu pelo lembrete, nem me liguei no momento que fiz!

2023-01-17 03:24 UTC, m7he4rt commented
@joaobispo2077 esse PR já está pronto ? A gente mergeou uma explicação do next no PR #95  seria interessante talvez reestruturar as páginas.

2023-09-04 23:21 UTC, closed without merging