Adiciona Tópico de estados
he4rt/react4noobs pull request #73
Opened 2021-06-30 15:35 UTC by Bluniz

Adiciona tópico de estados com Class Components para ter embasamento para poder falar sobre Ciclos de vida e futura atualização no tópico de hooks.

2021-06-30 16:25 UTC, jos3s requested changes

2021-06-30 16:25 UTC, jos3s commented on docs/Iniciando com React/5-Estados.md
> +<p>Suponha que tu faça uma aplicação de contador, quando tu apertar start ele sairá do 0 e ficará mudando. Vemos aqui que o estado inicial da aplicação é 0 e conforme ele vai sendo alterado o valor e
É necessário usar a tag p aqui? É sempre bom usar apenas elementos HTML quando necessários

2021-06-30 16:25 UTC, jos3s commented on docs/Iniciando com React/5-Estados.md
> +Neste capítulo vc entenderá o que são **Estados** no React.
Seria bom não utilizar o 'vc'

2021-06-30 16:25 UTC, jos3s commented on docs/Iniciando com React/5-Estados.md
> +<p>Com o conceito de imutabilidade, sempre iremos definir novos dados ao invez de modificar o dado.
É necessário usar a tag p aqui? É sempre bom usar apenas elementos HTML quando necessários

2021-06-30 16:45 UTC, Bluniz commented on docs/Iniciando com React/5-Estados.md
> +<p>Suponha que tu faça uma aplicação de contador, quando tu apertar start ele sairá do 0 e ficará mudando. Vemos aqui que o estado inicial da aplicação é 0 e conforme ele vai sendo alterado o valor e
Nessa parte é, pois precisava pular linha e seria mais interessante lançar m p que um br

2021-06-30 16:46 UTC, Bluniz commented on docs/Iniciando com React/5-Estados.md
> +<p>Com o conceito de imutabilidade, sempre iremos definir novos dados ao invez de modificar o dado.
Nessa parte é, pois precisava pular linha e seria mais interessante lançar m p que um br

2021-06-30 16:47 UTC, Bluniz commented on docs/Iniciando com React/5-Estados.md
> +Neste capítulo vc entenderá o que são **Estados** no React.
Corrigido!

2021-06-30 16:51 UTC, jos3s commented on docs/Iniciando com React/5-Estados.md
> +<p>Com o conceito de imutabilidade, sempre iremos definir novos dados ao invez de modificar o dado.
Você pode pular linha no markdown, apenas deixando uma linha vazia entre os conteúdos ou dando dois espaços ao fim de um texto

2021-06-30 16:52 UTC, jos3s commented on docs/Iniciando com React/5-Estados.md
> +## Oque é?
Lembrar de separar as palavras aqui

2021-06-30 16:54 UTC, Bluniz commented on docs/Iniciando com React/5-Estados.md
> +## Oque é?
Corrigido!

2021-07-02 18:54 UTC, Bluniz commented on docs/Iniciando com React/5-Estados.md
> +<p>Com o conceito de imutabilidade, sempre iremos definir novos dados ao invez de modificar o dado.
Resolvido.

2021-07-02 22:24 UTC, kjkGustavo approved these changes

2021-07-02 22:24 UTC, merged