Feature/components lifecycle
he4rt/react4noobs pull request #74
Opened 2021-07-05 00:53 UTC by Bluniz

2021-07-05 09:43 UTC, m7he4rt requested changes

2021-07-05 09:43 UTC, m7he4rt commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +  > Para todos os exemplos utilizaremos umabiblioteca chamada Axios para lidar com asrequisições, ela possui algumas vantagens emrelação a fetch api nativa do JS mas vocêpode utilizar o que tu bem en
Faltou alguns espaços aqui mano

2021-07-05 09:43 UTC, m7he4rt commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +## Conclusão
Nesse tópico faltou alguns espaços também

2021-07-05 15:46 UTC, Bluniz commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +  > Para todos os exemplos utilizaremos umabiblioteca chamada Axios para lidar com asrequisições, ela possui algumas vantagens emrelação a fetch api nativa do JS mas vocêpode utilizar o que tu bem en
Corrigido!

2021-07-05 19:01 UTC, kjkGustavo requested changes

2021-07-05 19:01 UTC, kjkGustavo commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +**Devo alertar novamente que essa funçãoéutilizada em casos muito raros e nãoérecomendado ficar mexendo nela sem um motivo concreto.**
espaços

2021-07-05 19:01 UTC, kjkGustavo commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +Essa é uma parte do ciclo quase nãoutilizada, pois existem diversos problemas.Atualmente no React é recomendando o usar ocomponentDidMount.
espaço

2021-07-05 19:01 UTC, kjkGustavo commented
Ué ficou `Outdated`, fiz alguma merda kk

2021-07-05 19:03 UTC, kjkGustavo requested changes

2021-07-05 19:03 UTC, kjkGustavo commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +![lifecycle image](https://www.notion.so/Ciclo-de-Vida-9cfadd42ca05429a94795803c5ccd216#a68de13b879648e884c0c92ff8b3cf5d)
imagem quebrada

2021-07-05 19:03 UTC, kjkGustavo commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +- **shouldComponentUpdate** → Essa função será chamada sempre que um estado ou propriedade for chamada. Nela tu pode decidir se o componente irá renderizar novamente ounão, por padrão ele re-renderiz
espaço no "não"

2021-07-05 19:03 UTC, kjkGustavo commented
Agora sim kk

2021-07-05 19:17 UTC, kjkGustavo commented
Tava lendo aqui para ver se tinha algum outro problema e acho que seria legal uma abordagem melhor ao invés de "tu" repetidamente? Para o leitor pode se tornar cansativo, mas de resto parabéns.

2021-07-05 20:02 UTC, Bluniz commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +- **shouldComponentUpdate** → Essa função será chamada sempre que um estado ou propriedade for chamada. Nela tu pode decidir se o componente irá renderizar novamente ounão, por padrão ele re-renderiz
Corrigido!

2021-07-05 20:02 UTC, Bluniz commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +![lifecycle image](https://www.notion.so/Ciclo-de-Vida-9cfadd42ca05429a94795803c5ccd216#a68de13b879648e884c0c92ff8b3cf5d)
Corrigido!

2021-07-05 20:03 UTC, Bluniz commented
> Tava lendo aqui para ver se tinha algum outro problema e acho que seria legal uma abordagem melhor ao invés de "tu" repetidamente? Para o leitor pode se tornar cansativo, mas de resto parabéns.

Muito obrigado pelo feedback mano! Fiz algumas alterações pra evitar tanto o uso, vou prestar mais atenção. Meio que virou um vicio ficar falando "tu" toda hora haeuheauea

2021-07-07 04:04 UTC, JVictorV requested changes
Cara, desculpa o review meio longo e alguns possíveis erros, a maioria das coisas são erros de português e mudanças simples na forma de apresentar algum tópico. Acho que o ponto mais importante a ser discutido que eu pontuei seria sobre os metodos legados

2021-07-07 04:04 UTC, JVictorV commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +- **componentWillUnmount** → Essa função ocorre sempre que um componente é removido de tela para garantir que elenão permaneça na DOM. É uma parte importante porém tu só mexe em casos muito específic
```suggestion
- **componentWillUnmount** → Essa função ocorre sempre que um componente é removido de tela para garantir que ele não permaneça na DOM. É uma parte importante porém tu só mexe em casos muito específicos, por exemplo: Limpar algum dado durante a desmontagem que você definiu durante a montagem(**componentDidMount**).
```

2021-07-07 04:04 UTC, JVictorV commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +Podemos concluir que o ciclo de vida dos componentes no React é algo muito bem trabalhado e interessante. Podemos não apenas entender mas também manipula-lospara realizar diversas ações.
```suggestion
Concluímos que o ciclo de vida dos componentes no React é algo muito bem trabalhado e interessante. Podemos não apenas entender mas também manipula-los para realizar diversas ações.
```

2021-07-13 15:14 UTC, Bluniz commented
Galera, foi mal a demora de revisar tudo. Ultimas semanas foram corridas, sobrou um tempo legal agora e bora ver tudo <3

2021-07-13 15:15 UTC, Bluniz commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +Nos próximos tópicos você aprenderá sobre oque são hooks, como utilizar e seus equivalentes em relação ao ciclo de vida!
Então nesse caso, talvez fosse melhor explicar durante o tópico de hooks?

2021-07-13 15:18 UTC, Bluniz commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +Essa é uma parte do ciclo quase não utilizada, pois existem diversos problemas. Atualmente no React é recomendando o usar ocomponentDidMount.
Bom, eu acho interessante a pessoa entender tudo que tinha pra entender o que tem agora. Porém concordo, acho que essa explicação da pra ir para outro ponto do componentDidMount , vou trabalhar aqui pra corrigir.

Sobre as versões 17+, tudo é basicamente componente funcional/hooks não achei que seria interessante explicar agora.
Coisa que tem que vir junto do tópico de Hooks

2021-07-13 15:19 UTC, Bluniz commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +A diferença pode parecer que é apenas o nome mas tudo muda completamente. Agora só estamos fazendo a requisição após o componente estar na DOM e não antes.
Vou corrigir o/

2021-07-13 15:21 UTC, Bluniz commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +    }
Nessa parte, eu achei mais "didático" por o if normal pois para quem talvez não tenha um conhecimento mais apurado de JS entenda melhor. 
O que tu acha?

2021-07-13 15:23 UTC, Bluniz commented
Vei, fiz pelo notion o artigo e quando passei pro Markdown chega deu vergonha da formatação indo pra disney KKKKKKKKKKK enfim

2021-07-16 01:01 UTC, Bluniz commented on docs/Iniciando com React/6-Ciclo-de-vida.md
> +Nos próximos tópicos você aprenderá sobre oque são hooks, como utilizar e seus equivalentes em relação ao ciclo de vida!
Concordo com tu, me passei em relação a equivalência. Vou deixar apenas a referência sobre com qual hook a pessoa encontra essa parte do ciclo

2021-07-17 02:37 UTC, kjkGustavo approved these changes

2021-08-02 05:54 UTC, m7he4rt approved these changes

2021-08-02 05:55 UTC, merged