Tópico sobre manipulação de Eventos no React
he4rt/react4noobs pull request #77
Opened 2021-07-19 12:08 UTC by Bluniz

2021-07-31 07:49 UTC, m7he4rt commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +    <form onSubmit={(event) => handleSubmit(event, id)}>
Aqui seria legal falar de como funciona para passar o segundo parâmetro, se é algo que o react faz por baixos dos panos ou algo assim, pois pode ficar confuso não passar ele explicitamente

2021-07-31 07:49 UTC, m7he4rt commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +# Manipulando Eventos
Seria legal citar exemplos de outros eventos como o onChange que é bastante utilizado também. Já que aqui basicamente o que você usou de exemplo é apenas o onClick e o onSubmit. 

Acho interessante também deixar a referência da [documentação do React](https://pt-br.reactjs.org/docs/events.html) sobre todos os eventos suportados.

2021-07-31 16:39 UTC, Bluniz commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +# Manipulando Eventos
Feito

2021-07-31 16:40 UTC, Bluniz commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +    <form onSubmit={(event) => handleSubmit(event, id)}>
Fiz as alterações e expliquei também, porém isso é conhecimento de JS. Pré requisito, a questão do camelCase, que funciona quase da mesma forma já foi explicada. Enfim, ta feito tb!

2021-07-31 16:40 UTC, Bluniz commented
@m7he4rt Quando puder da uma olhada no outro pull também, as alterações já foram feitas aguardando sua review o/

2021-08-02 04:51 UTC, JVictorV requested changes

2021-08-02 04:51 UTC, JVictorV commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +}
Isso daqui nao eh código valido, o id que vc ta passando pro handle submit nao ta definido, vai crashar a execução

2021-08-02 04:51 UTC, JVictorV commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +}
Aqui tmb

2021-08-02 04:51 UTC, JVictorV commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +    // Lembre-se que a ordemn nesse caso fica a sua escolha, se eu definisse na função que iria receber primeiro o id e o segundo seria o event daria o mesmo resultado.
```suggestion
    // Lembre-se que a ordem nesse caso fica a sua escolha, se eu definisse na função que iria receber primeiro o id e o segundo seria o event daria o mesmo resultado.
```

2021-08-02 04:51 UTC, JVictorV commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +  )
Faltou fechar o fragment aqui
```suggestion
  return(
    <>
      <input type="text" name="text" value={text} onChange={handleChange}>
      </input>
    </>
  )
```

2021-08-07 19:56 UTC, JVictorV requested changes

2021-08-07 19:56 UTC, JVictorV commented on docs/Iniciando com React/7-Manipulando Eventos.md
>      console.log("funfo", id);
Esse id logado não foi definido no context, recomendo tirar 
```suggestion
    console.log("funfo");
```

2021-08-07 19:56 UTC, JVictorV commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +
Achei que essa explicação aqui ficou bem confusa, o que você quis dizer?

2021-08-28 02:35 UTC, Bluniz commented on docs/Iniciando com React/7-Manipulando Eventos.md
> +
A ideia era que se possivel passar mais e diferentes variaveis. Porém lendo novamente ficou confuso. Vou remover

2021-08-28 02:37 UTC, Bluniz commented
Foi  mal a demora, como disse antes as coisas andam meio pegadas. Finalmente ta liberando muito, peço perdão pela demora, serio.

2021-09-15 13:16 UTC, merged